---
kind: Template
apiVersion: v1
labels:
  build: "${NAME}"
  template: "${NAME}-bc-template"
metadata:
  name: "${NAME}"
objects:
  - apiVersion: v1
    kind: ImageStream
    metadata:
      name: "${NAME}"
    spec:
      lookupPolicy:
        local: false
  - apiVersion: v1
    kind: BuildConfig
    metadata:
      name: "${NAME}"
      labels:
        buildconfig: "${NAME}"
    spec:
      completionDeadlineSeconds: 600
      failedBuildsHistoryLimit: 3
      output:
        to:
          kind: ImageStreamTag
          name: "${NAME}:latest"
      postCommit: {}
      resources:
        limits:
          cpu: 2000m
          memory: 2Gi
        requests:
          cpu: 1000m
          memory: 1Gi
      runPolicy: SerialLatestOnly
      source:
        contextDir: Metabase/openshift
        git:
          ref: "main"
          uri: "https://github.com/bcgov/iit-arch.git"
          type: Git
      strategy:
        dockerStrategy:
          buildArgs:
            - name: METABASE_VERSION
              value: "${METABASE_VERSION}"
          pullSecret:
            name: artifactory-creds
        type: Docker
      successfulBuildsHistoryLimit: 3
      triggers:
        - type: ConfigChange
parameters:
  - name: NAME
    displayName: Name
    description: The name assigned to all of the objects defined in this template.
    required: true
    value: metabase
  - name: METABASE_VERSION
    displayName: Metabase Version
    description: Version of Metabase to use
    required: true
    value: v0.43.1
