name: Update Metabase Image build and push.
description: Please provide the version of the metabase image to be build without the letter v, it will auto append v in the beginning while downloading. sample format is 0.43.1
body:
- type: input
  id: METABASE_VERSION
  attributes:
    label: Metabase Version
  validations:
    required: true
