apiVersion: v1
kind: Template
metadata:
  name: ${NAME}
  annotations:
    description: "Metabase PostgreSQL database"
    tags: "metabase-pg"
    iconClass: icon-js
labels:
  app: ${NAME}-${SUFFIX}
  app.kubernetes.io/part-of: ${NAME}-${SUFFIX}
parameters:
  - name: NAME
    description: Product name
    value: metabase-postgres
  - name: NAMESPACE
    description: Namespace to deploy to
    required: true
  - description: Password for the PostgreSQL connection user.
    from: "[a-zA-Z0-9]{16}"
    generate: expression
    name: DB_PASSWORD
  - description: Volume space available for data, e.g. 512Mi, 2Gi.
    displayName: Database Volume Capacity
    name: DB_PVC_SIZE
    required: true
    value: 1Gi
objects:
  - apiVersion: v1
    kind: Secret
    metadata:
      name: ${NAME}-${SUFFIX}
      labels:
        app: ${NAME}-${SUFFIX}
    stringData:
      database-name: "${NAME}"
      database-password: "${DB_PASSWORD}"
      database-user: "${NAME}"
  - kind: PersistentVolumeClaim
    apiVersion: v1
    metadata:
      name: ${NAME}-${SUFFIX}
      labels:
        app: ${NAME}-${SUFFIX}
    spec:
      accessModes:
        - ReadWriteMany
      resources:
        requests:
          storage: "${DB_PVC_SIZE}"
      storageClassName: netapp-file-standard
  - kind: ImageStream
    apiVersion: v1
    metadata:
      name: ${NAME}-${SUFFIX}
      labels:
        app: ${NAME}-${SUFFIX}
    spec:
      lookupPolicy:
        local: false
      tags:
        - name: ${NAME}-${SUFFIX}
          from:
            kind: DockerImage
            name: image-registry.openshift-image-registry.svc:5000/openshift/postgresql:12
          referencePolicy:
            type: Local
  - kind: DeploymentConfig
    apiVersion: v1
    metadata:
      name: ${NAME}-${SUFFIX}
      labels:
        app: ${NAME}-${SUFFIX}
    spec:
      replicas: 1
      strategy:
        type: Recreate
        recreateParams:
          timeoutSeconds: 600
        resources: {}
        activeDeadlineSeconds: 21600
      revisionHistoryLimit: 10
      template:
        metadata:
          name: ${NAME}-${SUFFIX}
          labels:
            app: ${NAME}-${SUFFIX}
        spec:
          volumes:
            - name: ${NAME}-${SUFFIX}
              persistentVolumeClaim:
                claimName: ${NAME}-${SUFFIX}
          containers:
            - name: ${NAME}-${SUFFIX}
              image: image-registry.openshift-image-registry.svc:5000/${NAMESPACE}/${NAME}-${SUFFIX}
              ports:
                - containerPort: 5432
                  protocol: TCP
              env:
                - name: POSTGRESQL_DATABASE
                  valueFrom:
                    secretKeyRef:
                      name: ${NAME}-${SUFFIX}
                      key: database-name
                - name: POSTGRESQL_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: ${NAME}-${SUFFIX}
                      key: database-password
                - name: POSTGRESQL_USER
                  valueFrom:
                    secretKeyRef:
                      name: ${NAME}-${SUFFIX}
                      key: database-user
              volumeMounts:
                - name: ${NAME}-${SUFFIX}
                  mountPath: "/var/lib/pgsql/data"
              livenessProbe:
                initialDelaySeconds: 30
                tcpSocket:
                  port: 5432
                timeoutSeconds: 1
              readinessProbe:
                exec:
                  command:
                    - /bin/bash
                    - -c
                    - pg_isready -h localhost -p 5432
                initialDelaySeconds: 20
                timeoutSeconds: 15
              terminationMessagePath: "/dev/termination-log"
              terminationMessagePolicy: File
              imagePullPolicy: Always
          restartPolicy: Always
          terminationGracePeriodSeconds: 30
          dnsPolicy: ClusterFirst
          schedulerName: default-scheduler
  - apiVersion: v1
    kind: Service
    metadata:
      labels:
        app: ${NAME}-${SUFFIX}
      name: ${NAME}-${SUFFIX}
    spec:
      ports:
        - name: postgresql
          nodePort: 0
          port: 5432
          protocol: TCP
          targetPort: 5432
      selector:
        name: ${NAME}-${SUFFIX}
      sessionAffinity: None
      type: ClusterIP
