version: "2.3"

services:
  quarkus-service:
    cpus: 2
    build:
      context: ../quarkus
      dockerfile: Dockerfile
    image: quarkus-service:latest
    mem_limit: 128m
    environment:
      - QUARKUS_DB_KIND=postgresql
      - QUARKUS_DATASOURCE_JDBC_URL=jdbc:postgresql://quarkus-db:5432/quarkus
      - QUARKUS_DATASOURCE_JDBC_USERNAME=quarkus
      - QUARKUS_DATASOURCE_JDBC_PASSWORD=quarkus123
      - CONSOLE_LOG_LEVEL=INFO
      - FILE_LOG_LEVEL=INFO
      - OIDC_AUTH_SERVER_URL=http://quarkus-keycloak:8190/auth/realms/master #secret
    ports:
      - "7997:8000"  # the HTTP endpoint
    depends_on:
      quarkus-db:
        condition: service_healthy
    networks:
      - quarkus
  quarkus-keycloak:
    image: quay.io/keycloak/keycloak:14.0.0
    environment:
      DB_VENDOR: postgres
      DB_ADDR: quarkus-kc-db:5432
      DB_DATABASE: quarkus
      DB_SCHEMA: public
      DB_USER: quarkus
      DB_PASSWORD: quarkus123
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
    healthcheck:
      test: [ "CMD-SHELL", "curl --fail http://localhost:8080/auth/realms/master" ]
      interval: 30s
      timeout: 10s
      retries: 10
      start_period: 1m
    ports:
      - "8190:8080"  # the HTTP endpoint
      - "9990:9990"  # the admin HTTP endpoint
    depends_on:
      quarkus-kc-db:
        condition: service_healthy
    networks:
      - quarkus
  quarkus-flyway:
    build:
      context: ../quarkus
      dockerfile: Dockerfile-migrations-local
    image: quarkus-api-migrations:latest
    container_name: quarkus-api-migrations
    environment:
      - FLYWAY_URL=jdbc:postgresql://quarkus-db:5432/quarkus
      - FLYWAY_USER=quarkus
      - FLYWAY_PASSWORD=quarkus123
      - FLYWAY_BASELINE_ON_MIGRATE=true
    depends_on:
      quarkus-db:
        condition: service_healthy
    networks:
      - quarkus
  quarkus-kc-db:
    image: postgres
    mem_limit: 128m
    environment:
      - POSTGRES_USER=quarkus
      - POSTGRES_PASSWORD=quarkus123
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U quarkus" ]
      interval: 5s
      timeout: 5s
      retries: 6
    ports:
      - "5433:5432"
    networks:
      - quarkus
  quarkus-db:
    image: postgres
    mem_limit: 128m
    environment:
      - POSTGRES_USER=quarkus
      - POSTGRES_PASSWORD=quarkus123
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U quarkus"]
      interval: 5s
      timeout: 5s
      retries: 6
    ports:
      - "5431:5432"
    networks:
      - quarkus

networks:
  quarkus:
    driver: bridge
