name: metabase-image-builder-on-issue

env:
  IMAGE_REGISTRY: ghcr.io/${{ github.repository_owner }}/nr-arch-templates
  IMAGE_REGISTRY_USER: ${{ github.actor }}
  IMAGE_REGISTRY_PASSWORD: ${{ github.token }}
  APP_NAME: 'metabase'

on:
  issues:
    types: [opened, edited]

jobs:
  build-metabase-image:
    name: Build Metabase Image.
    runs-on: ubuntu-20.04
    defaults:
      run:
        working-directory: Metabase
    steps:
      
      - name: Check out repository
        uses: actions/checkout@v2
        
      - name: Issue Forms Body Parser
        id: parse
        uses: zentered/issue-forms-body-parser@v1.5.0
      
      - name: check if build is required.
        id: check
        run: |
          echo "Issue body : ${{ steps.parse.outputs.data }}"
          MB="${{ JSON.stringify(steps.parse.outputs.data) }}" | jq -r '.["metabase-version"].text'
          echo "MB IS $MB"
          # Check if version paramter is given.
          METABASE_VERSION=${{ steps.parse.outputs.data['metabase-version'].text }}
          if [ -z $METABASE_VERSION ]
          then
            echo "::set-output name=build::false"
            exit 0
          fi
          echo "::set-output name=build::true"
          #
      
      - name: Set up Docker Buildx
        if: steps.check.outputs.build == 'true'
        uses: docker/setup-buildx-action@v2
      
      - name: Cache Docker layers
        if: steps.check.outputs.build == 'true'
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-
      
      - name: Log in to the Container registry
        if: steps.check.outputs.build == 'true'
        uses: docker/login-action@v2
        with:
          registry: ${{ env.IMAGE_REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Build and push Metabase image
        if: steps.check.outputs.build == 'true'
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: |
            "${{ env.IMAGE_REGISTRY }}/${{ env.APP_NAME }}:${{ steps.parse.outputs.data.METABASE_VERSION }}"
            "${{ env.IMAGE_REGISTRY }}/${{ env.APP_NAME }}:latest"
          cache-from: type=gha
          cache-to: type=gha,mode=max
          file: |
            ./Metabase/openshift/.pipeline/Dockerfile.openshift
          build-args: |
            METABASE_VERSION=${{ github.event.inputs.METABASE_VERSION }}
