name: confluence-crud

env:
  CONFLUENCE_USER_NAME: ${{ secrets.CONFLUENCE_USER_NAME }}
  CONFLUENCE_TOKEN: ${{ secrets.CONFLUENCE_TOKEN }}
  BASE_URL: ${{ secrets.CONFLUENCE_URL }}
  PAGES: "120392107"

on:
  workflow_dispatch:
  #pull_request:
  #  branches:
  #    - main
  #  paths:
  #    - 'apis/Go/fiber/**'

jobs:
  crud-confluenc:
    name: Get and update contents from confluence
    runs-on: ubuntu-20.04
    defaults:
      run:
        working-directory: confluence/script
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Add Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'

      - uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install Dependencies
        run: npm ci

      - name: process script
        run: |
          node index.js

      - name: Commit files  # transfer the new html files back into the repository
        run: |
          git config --local user.name  ${{ github.actor }}
          ls -lrt
          git add ../confluence/pages
          git commit -m "Adding or updating the confluence pages"
      - name: Push changes  # push the output folder to your repo
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          force: true

