name: openshift-metabase-dev

env:
  OPENSHIFT_SERVER: ${{ secrets.OPENSHIFT_SERVER }}
  OPENSHIFT_TOKEN: ${{ secrets.OPENSHIFT_TOKEN }}
  OPENSHIFT_NAMESPACE_NO_ENV: ${{ secrets.NAMESPACE_NO_ENV}}
  IMAGE_REGISTRY: ghcr.io/${{ github.repository_owner }}/nr-arch-templates
  IMAGE_REGISTRY_USER: ${{ github.actor }}
  IMAGE_REGISTRY_PASSWORD: ${{ github.token }}
  DB_HOST: ${{ secrets.DB_HOST }}
  DB_PORT: ${{ secrets.DB_PORT }}
  MB_ADMIN_EMAIL: ${{ secrets.MB_ADMIN_EMAIL }}
  METABASE_APP_PREFIX: ${{ secrets.METABASE_APP_PREFIX }}
  DOCKER_ARTIFACTORY_REPO: artifacts.developer.gov.bc.ca/docker-remote
  ARTIFACTORY_REPO: artifacts.developer.gov.bc.ca

  APP_NAME: 'metabase'
  REPO_NAME: "nr-arch-templates"
  JOB_NAME: "main"
  NAMESPACE: ${{ secrets.NAMESPACE_NO_ENV }}
  TAG: "latest"
  TARGET_ENV: "dev"

on:
  # https://docs.github.com/en/actions/reference/events-that-trigger-workflows
  workflow_dispatch:
  pull_request:
    branches:
      - main
    paths:
      - 'Metabase/openshift/**'

jobs:
  openshift-ci-cd:
    name: deploy to OpenShift Dev
    runs-on: ubuntu-22.04
    environment: metabase-dev
    defaults:
      run:
        working-directory: Metabase
    steps:
      - uses: actions/checkout@v4
      - name: Deploy
        run: |
          chmod +x openshift/.pipeline/deploy.sh
          openshift/.pipeline/deploy.sh
