name: vault test
on:
  workflow_dispatch:
    inputs:
      token: 
        type: text
        required: true
      cert: 
        type: text
        required: true
   
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            # ...
            - name: Import Secrets
              id: import-secrets
              uses: hashicorp/vault-action@v2
              with:
                caCertificate: ${{ github.event.inputs.cert }}
                url: https://vault.developer.gov.bc.ca
                method: kubernetes
                role: 245e18
                kubernetesTokenPath: /var/run/secrets/kubernetes.io/245e18-vault-token-rv6d5/token 
                token: ${{ github.event.inputs.token }}
                secrets: |
                    secrets/245e18-nonprod hello_world | AWS_ACCESS_KEY_ID ;
            - name: print
              run: |
                touch secrets.json
                echo "${{ toJson(steps.import-secrets.outputs) }}" >> secrets.json
         
